WAITFOR DELAY '00:00:05';
GO

CREATE DATABASE schematic_test_dst ;
GO
CREATE DATABASE schematic_test_src ;
GO
WAITFOR DELAY '00:00:05';
GO
CREATE LOGIN [schematic] WITH PASSWORD='schematic123', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
GO
WAITFOR DELAY '00:00:05';
GO

GO
CREATE LOGIN [ssrs] WITH PASSWORD='ssrs', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
GO

USE [schematic_test_dst]
GO

CREATE SCHEMA DestSchema;
GO

CREATE USER [schematic] FOR LOGIN [schematic] WITH DEFAULT_SCHEMA=[dbo];
GO

CREATE USER [ssrs] FOR LOGIN [ssrs] WITH DEFAULT_SCHEMA=[dbo];
GO

CREATE ROLE db_schematic_role;
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::dbo TO db_schematic_role;
GO
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, REFERENCES TO db_schematic_role;
GO
CREATE ROLE db_mi_role;
GO
CREATE SCHEMA mi AUTHORIZATION [ssrs];
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE ON schema::mi to db_mi_role;
GO
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION TO db_mi_role;
GO
GRANT EXECUTE, SELECT, VIEW DEFINITION ON schema::dbo TO db_mi_role;
GO
CREATE SCHEMA Tzdb AUTHORIZATION [dbo];
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::Tzdb TO db_schematic_role;
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::Tzdb TO db_mi_role;
GO

ALTER ROLE db_schematic_role ADD MEMBER schematic;
GO

ALTER ROLE db_mi_role ADD MEMBER [ssrs];
GO

EXEC master..sp_addsrvrolemember @loginame = N'schematic', @rolename = N'sysadmin'
GO

USE [schematic_test_src]
GO

CREATE SCHEMA SourceSchema;
GO